### ISSUE TITLE
React-stamp

### ISSUE THREAD

**Issue by drkhannah** [petehunt/react-roadmap#4]
What are your thoughts on pure componets and eric elliott's react-stamp library, and his advice to not use es6 classes with react. He calls it "class free react"

**Comment by petehunt** [comment]
I don't know `react-stamp` at all, and I don't think it has a lot of traction.

I think pure components -- i.e. ones without state -- are great. I tend to not use the function component syntax since it means I'm going to have to do a bit more typing to refactor it to use lifecycle hooks or state, but that's a personal preference.

I too avoid ES6 classes for React components, since most big projects tend to depend on a handful of mixins. Facebook also does not use ES6 class syntax for React components.

Do you think this needs to be worked into this guide?

**Comment by petehunt** [comment]
(closing issue, please reopen if you think it needs to be worked into the guide)

**Comment by drkhannah** [comment]
React-stamp is the react version of the stampit library, a small library for composing javascript objects, if anything its a great way to learn composition and get away from classical inheritance.

I think that at least mentioning that facebook doesn't use the es6 class syntax would be great because i see a bunch of tutorials out there using it. Anytime i see this used in books or tutorials i stop reading them.

I feel classes lead newbies down the wrong path since they should prefer composition over classical inheritance, and that classes are the single most harmful addition to es6. They were added for people that came from other languages and dont truly understand prototypal inheritance, prototype delegation and composition in javascript

This is great stuff youve posted here, whats your twitter handle? I want to start following you

Mine is @papaderekfresh and i tweet about not using es6 classes all the time to get the word out

And if you like what you see, let me know if there is an opening for a fullstack javascript dev at facebook ; )
